apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-group
spec:
  replicas: 2 # Two replicas to show load balancing, only one will get the message
  selector:
    matchLabels:
      app: consumer-group
  template:
    metadata:
      labels:
        app: consumer-group
    spec:
      containers:
      - name: consumer
        image: kafka-demo-app:latest
        env:
        - name: APP_MODE
          value: "CONSUMER"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "demo-topic"
        - name: CONSUMER_GROUP_ID
          value: "shared-group"
